### ISSUE TITLE
Front End: Displaying peer messages

### ISSUE THREAD

**Issue by GMOkeefe** [hondarider29/SoundByte#28]
Story #5 

UI page that displays, to one user, a list of the users that they have previous messaging history with, so they can select them and go that chat page.

**Comment by joesobo** [comment]
ETA: 3 Hours

**Comment by hondarider29** [comment]
7

**Comment by joesobo** [comment]
Unfinished: 4

**Comment by garretpoole** [comment]
change chat to be individualized

**Comment by joesobo** [comment]
finished: 6
