### ISSUE TITLE
Front End: send and receive messages

### ISSUE THREAD

**Issue by joesobo** [hondarider29/SoundByte#57]
Estimated time: 3 hours

**Comment by GMOkeefe** [comment]
Unfinished: 5

**Comment by joesobo** [comment]
Remaining ETA: 4 hours

**Comment by hondarider29** [comment]
7

**Comment by hondarider29** [comment]
Remaining ETA: 2

**Comment by rramani1230** [comment]
Issue is completed. Person to person messaging now works.

**Comment by hondarider29** [comment]
How much time was spent on this @rramani1230

**Comment by rramani1230** [comment]
6 Hours across 2 sprints
